---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: apple-dots
# description will be included in the image's metadata
description: MacBookPro 14,2 work maybe??? 

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable # latest is also supported if you want new updates ASAP

modules:

- type: files
  files:
    - source: system/etc
      destination: /etc
    - source: system/usr
      destination: /usr

  - type: script
    scripts:
      # pull Wifi/BT firmware sources from arch-t2 mirror
      # using asahi-installer fork to package for use in fedora
      # it's hacky <3
      - apple-bcm-firmware.sh #also bagel added the config file hopefully
  
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
