---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: apple-dots
# description will be included in the image's metadata
description: MacBookPro14,2 work maybe???

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable # latest is also supported if you want new updates ASAP

stages:
- name: firmwarez
  from: docker.io/library/debian:stable-slim
  modules:
  - type: script
    scripts:
      - upd8.sh
      # pull Wifi/BT firmware sources from arch-t2 mirror
      # using asahi-installer fork to package for use in fedora
      # it's hacky <3
      - apple-bcm-firmware.sh
      # download *part of* bootcamp driver pack, extract necessary files, dump em :)
      - camera-calibration.sh

modules:
- type: files
  files:
  - source: system/etc
    destination: /etc
  - source: system/usr
    destination: /usr
#  - source: system/lib/firmware # brcmfmac43602-pcie.txt config taken from https://github.com/Dunedan/mbp-2016-linux/issues/47#issuecomment-663926000
#    destination: /lib/firmware
  - source: system/lib
    destination: /lib

- type: copy
  from: firmwarez
  src: /out/lib/firmware/
  dest: /lib/firmware

- type: rpm-ostree
  # repos:
  # - https://copr.fedorainfracloud.org/coprs/mulderje/facetimehd-kmod/repo/fedora-%OS_VERSION%/mulderje-facetimehd-kmod-fedora-%OS_VERSION%.repo
  
  install:
  - tiny-dfr
#  - bpftune # oh it isn't available in the repos lol; if i ever feel like it, gotta compile at build
#  - facetimehd-kmod # webcam kernel module
  - mbpfan

#- type: akmods
#  install:
#  - facetimehd # available as an akmod

- type: systemd
  system:
    enabled:
    - mbpfan.service
    - mac-wifi-txpower.service
#    - dirty-centisecs.service
    - memory-tweaks-gidro.service

- type: initramfs # rebuild initramfs # only ostree?
- type: signing # this sets up the proper policy & signing files for signed images to work fully
